### ISSUE TITLE
ssllabs.com cert chain broken for https://www.ssllabs.com/ssltest/viewMyClient.html ?

### ISSUE THREAD

**Issue by bknowles** [ssllabs/ssllabs-scan#126]
So, when I go to the page at "[https://www.ssllabs.com/ssltest/viewMyClient.html](SSL/TLS Capabilities of Your Browser)", I get SSL certificate errors that show up in Calomel SSL Validation, and in SSLeuth, using Firefox 37.0.2.

Here's the first one:

![screen shot 2015-05-11 at 11 36 51 pm](https://cloud.githubusercontent.com/assets/1151895/7580296/eba57b64-f837-11e4-90cf-b30d0c59cf44.png)

And the second:

![screen shot 2015-05-11 at 11 37 17 pm](https://cloud.githubusercontent.com/assets/1151895/7580297/f1eed6aa-f837-11e4-91de-f35da0208ee7.png)

<br>

If this is because of the "Mixed Content Handling" tests shown at the bottom of the page, you might want to put those on a separate page, or clarify the information regarding the types of errors that might result.

**Comment by ivanr** [comment]
That page does have insecure content, which is necessary in order to test if browser support mixing secure resources with insecure resources. There's a message about it at the very bottom ("These tests might cause a mixed content warning in your browser. That's expected."), but it's not very prominent. So I suppose that's what your plugin is warning about.

**Comment by bknowles** [comment]
I think if the message at the bottom could be clarified, and maybe moved to the top of the page, that would resolve the problem.  Thanks!
