### ISSUE TITLE
OCSP stapling should not be green "Yes" for sites with revoked certificates

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#142]
https://www.ssllabs.com/ssltest/analyze.html?d=rc4.io&s=82.163.77.97

> Revocation status	Revoked INSECURE
Trusted No NOT TRUSTED

![image](https://cloud.githubusercontent.com/assets/10382329/7896336/6a8d08fe-06be-11e5-8be8-c02dcf866e31.png)

> OCSP stapling Yes

![image](https://cloud.githubusercontent.com/assets/10382329/7896294/c8e04e90-06bc-11e5-8840-75cfd623ee4d.png)

![image](https://cloud.githubusercontent.com/assets/10382329/7896328/1b19d5b8-06be-11e5-9ee5-fff3d10f6bad.png)

How it should be:
> OCSP stapling False information provided INSECURE

![image](https://cloud.githubusercontent.com/assets/10382329/7896315/63e79b46-06bd-11e5-83ad-7381d079f7cf.png)

**Comment by selecadm** [comment]
Unlike Microsoft IIS, nginx seems not to provide stapled OCSP for revoked certificates. Any ideas?

Anyway, this server has now gone offline.

**Comment by mdounin** [comment]
If your goal is to make "Google Chrome unable to open a site", then you are using a wrong mechanism. Just shutting down a server is a much better solution.

**Comment by ivanr** [comment]
This is difficult to test because I don't have a revoked certificate. The rumour is that Apache doesn't check stapled OCSP responses so... if you could setup an Apache host with that certificate, you could try SSL Labs against it.
Looking at my code, stapled OCSP responses that are incorrect are displayed as "invalid". It's possible that, even though the certificate was revoked, the actual stapled OCSP response was valid.
