### ISSUE TITLE
server throws an error with trailing dot in domain

### ISSUE THREAD

**Issue by J0WI** [ssllabs/ssllabs-scan#151]
https://ssllabs.com./ throws an error. This affects all subdomains.

**Comment by selecadm** [comment]
Bad request for HTTPS, but not for HTTP. http://ssllabs.com./ correctly redirects to https://www.ssllabs.com/ (but first you need to delete ssllabs.com from HSTS cache).

BTW, Internet Explorer warns about certificate mismatch in such cases.

**Comment by ivanr** [comment]
The root cause is a mismatch between the site hostname used at the HTTP level and the hostname provided in the SNI extension. It seems that browsers (tested Chrome, Firefox, and Safari) normalize the HTTP hostname but leave the SNI version as-is. At the same time, Apache refuses to serve HTTP requests when there is a mismatch.
