### ISSUE TITLE
Handshake Simulation: Reference Browsers Update

### ISSUE THREAD

**Issue by RobTho** [ssllabs/ssllabs-scan#176]
does these browsers still need to be reference ?
- IE8-10 @W7  (will be EOS by End of 2015) cause replace by IE11
- Safari @OSX 10.8 (EOS during 2015)
- Safari @iOS 6 and iOS 7 (already EOS)

**Comment by J0WI** [comment]
Note that XP/Vista users can't upgrade their IE.
iPhone 3/ iPod touch 4 users even can't use a modern browser.

**Comment by fishouttah20** [comment]
As much as I wish EOS meant people stopped using those browsers, having done detailed analysis of user agents for a company with a large web presence, people happily continue to use massively out of date and unsupported browsers - so it's helpful to see what those users will negotiate.

**Comment by ivanr** [comment]
@RobTho you haven't given us any reason to remove their "reference" status. In general, the fact that they are EOL-ed doesn't mean that they are not used any more or that they're not important.

**Comment by selecadm** [comment]
> you haven't given us any reason to remove their "reference" status

SSL Labs requires negotiating ephemeral key exchange with iOS 6 for A-grade security, despite the fact that negotiating (EC)DHE makes session vulnerable to MITM-attacks, since iOS 6 doesn't verify certificates. This makes providing PFS to iOS 6 a security theater. iOS 6 verifies certificates only in case of negotiating static RSA.

Also, as of 20 July 2015, iOS 6 market share is 2%.

![image](https://cloud.githubusercontent.com/assets/10382329/8922455/d098445a-34eb-11e5-9f9b-37ac8d304eea.png)

**Comment by nextPrime** [comment]
>Servers that support both RSA and ECDHE without their own preference negotiate RSA with "IE 8-10 / Win 7", since this client prioritizes RSA above ECDHE, making such servers impossible to get an A.

Actually the cipher suite order for [IE 8-10 / Win7](https://www.ssllabs.com/ssltest/viewClient.html?name=IE&version=8%2d10&platform=Win%207) on SSL Labs is **wrong**. it should be the same as IE 11 except that IE 8-10 doesn't have TLS 1.1 and 1.2 enabled.

**Comment by RobTho** [comment]
Hi 
i do not mean't remove them from browser list.
I just thought it maybe is time to reconsider the "R" status. So 2% Marketshare is still worth to get a "R" Status ?
