### ISSUE TITLE
webmail.icloud.com and mail.icloud.com report "F", but website reports C

### ISSUE THREAD

**Issue by frnkblk** [ssllabs/ssllabs-scan#189]
Using the v1.19.33 (criteria version 2009j).

**Comment by selecadm** [comment]
API gives an F to these sites because it detects new variations of the POODLE attack against TLS servers.
https://vivaldi.net/en-US/blogs/entry/there-are-more-poodles-in-the-forest

![image](https://cloud.githubusercontent.com/assets/10382329/8891271/4b4f29f6-332b-11e5-8e00-7f2f3223cb18.png)

![image](https://cloud.githubusercontent.com/assets/10382329/8891275/708e1b1e-332b-11e5-9b2f-1f3c7362f9f6.png)

Poor Apple :(.

**Comment by frnkblk** [comment]
But the website shows a C....

![image](https://cloud.githubusercontent.com/assets/4812492/8891290/28940dec-32e9-11e5-94f4-aa434879c968.png)

Or is the website using an old set of of tests and the API using a new set of tests?

**Comment by selecadm** [comment]
> Or is the website using an old set of of tests and the API using a new set of tests?

Yes. The website is v1.18.1 currently.

> I also noticed that the IP address in your screenshot was different than any of mine.

Apple returns different IPs for different client locations.

**Comment by frnkblk** [comment]
Thanks, yes, issue is found with the dev site:

![image](https://cloud.githubusercontent.com/assets/4812492/8891360/dfb50632-32eb-11e5-83fa-f541c88faf0e.png)

**Comment by ivanr** [comment]
The _production_ web site and API run from the same code base. If you consistently use www.ssllabs.com and api.ssllabs.com then the results will be the same. @selecadm is correct The version on the dev server detects another POODLE TLS variant. Development web site and API should provide the same results.
