### ISSUE TITLE
HSTS on subdomains

### ISSUE THREAD

**Issue by dabaer** [ssllabs/ssllabs-scan#210]
Hello, the scan doesn't appear to honour the includeSubdomains; option within and HSTS header. I am able to show A+ with HSTS support for the root domain, but a subdomain with the exact same configuration shows as not supporting HSTS and gets limited to A.

**Comment by ivanr** [comment]
Yes, that's correct and it's the intended behaviour. If you want enable HSTS on a hostname you should do it directly, rather than rely on includeSubDomain running on the parent. The includeSubDomains directive is mostly useful as a safety net (to catch mistakes) and to defend against situations where a MITM can make up a subdomain (because she controls the wire, she controls the DNS) and attack from there (cookies in particular).

**Comment by selecadm** [comment]
A client isn't aware of HSTS includeSubDomains set on a main domain in case of no requests made to it. Either set HSTS on a subdomain.example.com also or force clients to make a request to example.com by putting a pixel or zero-size iframe.

**Comment by dabaer** [comment]
Both configurations had the same options set (ie HSTS), I assume that's what you mean by setting it directly. I had tried setting includeSubdomains in that subdomains configuration as I misunderstood the purpose of the directive. Either way, ssl-labs does not produce the expected result of setting HSTS on any subdomain directly. As well, sending a request to the root domain is not acceptable.

**Comment by ivanr** [comment]
I am not sure I understand fully. Please leave a link to the report and I will look into it.
