### ISSUE TITLE
Root certificate is incorrectly reported

### ISSUE THREAD

**Issue by mkstead** [ssllabs/ssllabs-scan#247]
help.macu.com

expiration date of root cert is incorrect. In addition, the site is flagged because the root is using SHA1. Other sites are not flagged though even though the root is SHA1

**Comment by selecadm** [comment]
I haven't even looked at the report yet, but I think you are confused because of the site sending SHA1 intermediate signed by the root not trusted by Mozilla. Maybe it had been trusted previously, but recently distrusted because it's 1024-bit. The site probably uses Symantec (either VeriSign or Thawte brand) cert. If VeriSign, the site sends "VeriSign Class 3 Public Primary Certification Authority G5" SHA1 intermediate under "Class 3 Public Primary Certification Authority" 1024-bit root. If Thawte, the site sends "thawte Primary Root CA" SHA1 intermediate under "thawte Premium Server CA" 1024-bit root. For a long time Symantec had been providing obsolete chains to their customers. Now it seems they finally dropped this SHA1 pseudo-root stupidity, even Symantec Cryptoreport throws a warning for such sites.

Let's see if I am right.

**Comment by selecadm** [comment]
Great! There is a warning "_Intermediate_ certificate has a weak signature".

The cert was issued only 10 days ago, and I am not sure what went wrong, but the site's chain is broken. Even Symantec tool agrees:

![image](https://cloud.githubusercontent.com/assets/10382329/11016605/503a3d88-8598-11e5-8aae-ae2e6f01b25d.png)
