### ISSUE TITLE
Android 5.0 and 3DES

### ISSUE THREAD

**Issue by ocdtrekkie** [ssllabs/ssllabs-scan#256]
On a server handshake simulation, I got the following:

Android 5.0.0  TLS 1.0   TLS_RSA_WITH_3DES_EDE_CBC_SHA (0xa)   No FS  

This seems like it may be an error, according to http://developer.android.com/about/versions/android-5.0-changes.html

"MD5, **3DES**, export, and static key ECDH cipher suites are now disabled,"

Also, the person I was checking this for has Android 5.1, and it doesn't look like handshake simulation has been updated for a couple of Android releases now.

**Comment by ocdtrekkie** [comment]
Reference: k9mail/k-9#892

**Comment by selecadm** [comment]
True.

https://developer.android.com/reference/javax/net/ssl/SSLSocket.html

> Cipher suite	Supported (API Levels)	Enabled by default (API Levels)
SSL_RSA_WITH_3DES_EDE_CBC_SHA	9+	9–19

Android 5.0 == API Level 21

Other suites:
TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA
TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA
TLS_RSA_WITH_RC4_128_MD5

**Comment by ivanr** [comment]
I see that's what the documentation is saying, but the Android 5.0.0 simulation was captured on an actual Nexus device. The capabilities are exactly as sent by "Mozilla/5.0 (Linux; Android 5.0; Google Nexus 7 2013 - 5.0.0 - API 21 - 1200x1920 Build/LRX21M) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/37.0.0.0 Safari/537.36".

I think on Android the situation with simulations is particularly messy because there are so many devices with potentially different capabilities.

**Comment by drwetter** [comment]
With a real Android 5.0.1 device I have EXACTLY the same as https://www.ssllabs.com/ssltest/viewClient.html?name=Android&version=5.0.0. So  
TLS_RSA_WITH_3DES_EDE_CBC_SHA,
TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA, 
TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA
TLS_RSA_WITH_RC4_128_MD5  are all enabled.

Only no SSLv3 -- that is the only difference.

Don't know how to retrieve the API version. It's not in the sessting
