### ISSUE TITLE
OpenSSL 1.0.2: Protocol or cipher suite mismatch

### ISSUE THREAD

**Issue by dkleeblatt** [ssllabs/ssllabs-scan#281]
On our site we get this error even if protocol and appropriate ciphers are enabled:
OpenSSL 1.0.2  R		Protocol or cipher suite mismatch

**Comment by ivanr** [comment]
Please check if you can connect to your site using OpenSSL 1.0.2. If you can and SSL Labs is incorrect, please attach a link to the report that contains your server information.

**Comment by dkleeblatt** [comment]
Hi, I can see it for sites runnning on Netscaler appliances. Up to Report v1.20 it was working correctly, since 1.21 it is shown as mismaatch.

here are two examples:
https://www.ssllabs.com/ssltest/analyze.html?d=access.fks.de&hideResults=on
https://www.ssllabs.com/ssltest/analyze.html?d=access.sharp.eu&hideResults=on

**Comment by ivanr** [comment]
The simulation is correct. However the problem is that the simulated version of OpenSSL sends "http/2" as the only ALPN protocol, and the site (rightly) doesn't know what to do with it. It's probably something a newever 1.0.2 version fixes. I'll fix this bug by upgrading to the latest 1.0.2 version. Also, I'll improve the simulations to show what alert is returned when a connection fails.

**Comment by dkleeblatt** [comment]
HTTP/2 is now enabled on one of the Netscalers but the result is the same.

**Comment by ivanr** [comment]
The correct protocol string for HTTP is "h2", not "http/2". That's the problem. It might also be an issue that OpenSSL (the simulated version ) is not offerring "http/1.1" as fallback.

**Comment by dkleeblatt** [comment]
ok, I understand. Thanks for the information.

**Comment by ivanr** [comment]
In v1.22.8 (now running in dev) I replaced the incorrect OpenSSL 1.0.2 simulation with 1.0.2e. Everything seems in order now.
