### ISSUE TITLE
Scans do not verify OCSP signing certificates

### ISSUE THREAD

**Issue by woggle** [ssllabs/ssllabs-scan#301]
Some OCSP responders are misconfigured and use the wrong signing certificate, but SSLLabs does not detect this. For example, as of this writing, the OCSP responder for certificate www.poste.it gives an OCSP response using a certificate from the wrong CA (Postecom CA3 instead of Postecom CS3). SSLLabs's scan gives "ocspRevocationStatus" of 2 (certificate not revoked) rather than 3 (revocation check error).

**Comment by ivanr** [comment]
There's something else wrong with their signing certificate and that wasn't being detected either (due to a bug, signature validation wasn't attempted for OCSP responders, it was done only for stapled OCSP responses). It should work now on https://dev.ssllabs.com/ssltest/analyze.html?d=poste.it&hideResults=on&latest Thanks!
