### ISSUE TITLE
score adjustments

### ISSUE THREAD

**Issue by J0WI** [ssllabs/ssllabs-scan#38]
Referring to https://www.ssllabs.com/downloads/SSL_Server_Rating_Guide.pdf, servers that support SSL 3 and TLS 1.2 still got a score of 90%, even if they are vulnerable to POODLE (SSLv3).
But if a server does not support TLS 1.2, I got a score of 70%.

Same for RC4: Grade is B, but the score of key exchange can still be 90%. I found a server, that supports deprecated SSL 2 ciphers. Grade is F, because of SSL 2, but cipher strength and key exchange are still 80% and 90%.

Referring to https://www.ssllabs.com/downloads/SSL_Server_Rating_Guide.pdf, I also should get a much worse score with 3DES enabled, because it's only 112 bit. So with the current spec I should get a  score of 60% (with additional 256 suites enabled). But for the score, 3DES counts still as 168 bit.

**Comment by ivanr** [comment]
As a rule of thumb, if you wish to report scoring issues, please provide links to servers where the scoring is faulty. Otherwise I can't even begin to look into the reports.

That said, I am not going to look into these issues right now because I am about to start working on a brand new scoring criteria. One implemented, it's going to simplify and improve the grading. Thanks!
