### ISSUE TITLE
JSON unmarshal error

### ISSUE THREAD

**Issue by edimusrex** [ssllabs/ssllabs-scan#415]
This tool has been working great but as of today it started doing the following

> [ERROR] JSON unmarshal error: json: cannot unmarshal array into Go value of type map[string]string

Help would be appreciated

**Comment by anand-bhat** [comment]
The issues appears to be due to the type change for the `directives `attribute in `hpkpPolicy `and `hpkpRoPolicy `in the API.

Left: Old; Right: New

![image](https://cloud.githubusercontent.com/assets/7332442/19616264/f3e99b4e-982b-11e6-8465-1ecc16fc37c4.png)

![image](https://cloud.githubusercontent.com/assets/7332442/19616262/e53b9340-982b-11e6-95c7-34fdabf0d11d.png)

I was able to get the ssllabs-scan.go script working by chaging the type for `directives` from `map[string]string` to `[]map[string]string`

![image](https://cloud.githubusercontent.com/assets/7332442/19616281/57a4096c-982c-11e6-80f8-f87ac093f79c.png)

@bhushan5640 can probably confirm if this change was intended. The [changelog](https://community.qualys.com/docs/DOC-5737) hasn't been updated yet.

**Comment by bhushan5640** [comment]
ssllabs-scan client updated. kindly verify.

**Comment by anand-bhat** [comment]
Thanks, works for me!

**Comment by thorstenkampe** [comment]
Can we expect an updated release? For those of us who don't have a go compiler...

**Comment by bhushan5640** [comment]
ssllabs-scan client is updated/released. Just start using the new updated client.
Install the updated client: https://github.com/ssllabs/ssllabs-scan/blob/stable/ssllabs-scan.go

**Comment by gricuk** [comment]
And what about  Official stable binaries? ( https://github.com/ssllabs/ssllabs-scan/releases ) .
will Official stable binaries be updated?

**Comment by bhushan5640** [comment]
yest that needs to be updated, i will do that.

**Comment by bhushan5640** [comment]
ssllabs-scan client 1.4.0 released (https://github.com/ssllabs/ssllabs-scan/releases). Kindly verify !

**Comment by gricuk** [comment]
Thank you!

**Comment by sb-relaxt-at** [comment]
Thanks, works like a charm!

**Comment by seefood** [comment]
Fixed for me as well (`git pull && make`), Thanks! Recommend issue close...
