### ISSUE TITLE
Test for ticketbleed CVE-2016-9244 vulnerability

### ISSUE THREAD

**Issue by fishouttah20** [ssllabs/ssllabs-scan#458]
See ticketbleed.com for details. Believe it requires sending a 31byte session Ticket and looking for a non-matching 32byte session ticket in the response.

**Comment by bhushan5640** [comment]
Test deployed on dev.ssllabs.com
FYI, https://blog.qualys.com/ssllabs/2017/02/23/ticketbleed-detection-added-to-ssl-labs

**Comment by ivanr** [comment]
Today, the test was deployed in production, as part of the 1.28.3 roll-out.

**Comment by fishouttah20** [comment]
Is it available via the v2 and/or v3 API?

**Comment by bhushan5640** [comment]
It is available via API V3
API v3 doc: https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs-v3.md
API v3 client: https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-scan-v3.go

**Comment by huan086** [comment]
The scan is giving false positive for Windows Server. The server https://bleed.coursepad.co/ is Windows Server with TLS tickets enabled. It is not behind any F5 products.

https://nmap.org/nsedoc/scripts/tls-ticketbleed.html correctly report it as Not vulnerable

**Comment by drwetter** [comment]
FYI for some F5s which are vulnerable I didnt see the nse script raising its hand either. So I wouldn't take this as the holy grail. 

⁣-- 
Sent via mobile. Excuse my brevity, my typos and the autocorrection​

**Comment by bhushan5640** [comment]
@huan086 Filippo Ticketbleed test also marks it as vulnerable. https://filippo.io/Ticketbleed/#bleed.coursepad.co:443

Disable session tickets https://community.qualys.com/thread/17180-is-ticketbleed-cve-2016-9244-possible-in-a-non-f5-environment#comment-36766

**Comment by huan086** [comment]
@bhushan5640 the thing is that for the filippo test, they had explicitly stated

> *Note: there exist implementations other than F5 that exhibit a similar bug which might not have security implications.

While Windows behaviour is certainly a bug, it should not be considered vulnerable. There is no evidence of the server leaking initialized memory.

The bug has no real world consequence too, since Windows always issues session ID of 32 bytes. Thus, clients are only expected to be sending the server ID of 32 bytes.

The Ticketbleed test should give a conclusive yes by observing several packets and detecting non-zero padding to the session ID. The nmap implementation seems to be doing this.

Otherwise, for bugged implementation, show it as a yellow warning `Ticketbleed: Yes (inconclusive)` and that should not affect the overall rating
