### ISSUE TITLE
"ignore-mismatch" has no affect when "grade" option specified

### ISSUE THREAD

**Issue by fishouttah20** [ssllabs/ssllabs-scan#462]
when both -ignore-mismatch and -grade are specified, the output still only shows "T" for domains with trust issues instead of the grade when trust is ignored. 

Haven't had a need for this previously, but with the newly exposed Future grade functionality, I can't expose future grades without parsing the full JSON output.

**Comment by bhushan5640** [comment]
--ignore-mismatch	used to Proceed with assessments on certificate mismatch
It doesn't give the grade with trust issues are ignored. For that JSON needs to be parsed for "gradeTrustIgnored"

[API V3](https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs-v3.md) field "futureGrade" - next grade because of upcoming grading criteria changes, Null if there is no impact on current grade.

If you want to test if there is grade change for the sites with or without trust stores, You need to check if futureGrade field is present of not. And
If you are using  --grade option then you will see like "grade" -> "futureGrade"; else only one grade
eg. "T" -> "F"
"B" -> "C"
If there is grade impact on sites with trust issues and next grade is also "T" you will get
"T"  -> "T"

You can confirm grade impact by looking if there are two grades if not there is no impact.

**Comment by fishouttah20** [comment]
Understood. I guess then this would be a future feature request for a --gradeTrustIgnored option to complement the --grade option so that grade could be pulled without parsing all the JSON. We'll get our parsing updated to work with the v3 API so not a huge issue, but something to consider.

Thanks for all your work on the SSLLabs scanner, it's invaluable.

**Comment by bhushan5640** [comment]
Great.!! we will consider adding that option.
