### ISSUE TITLE
SSL Report: cz-uat.oriflame.com (137.116.206.54) wrong rating

### ISSUE THREAD

**Issue by dinesh-tyagi2003** [ssllabs/ssllabs-scan#490]
Please correct the rating for SSL Report: cz-uat.oriflame.com (137.116.206.54)
We have disabled SSL v2.0 on server for cz-uat.oriflame.com but in result its searching on 212.82.222.109	443	Yes	Yes	Vulnerable (same key with SSL v2) which is not our server and we don't no, can't manage it.
So please correct the rating.

**Comment by ivanr** [comment]
The report is correct. The nature of DROWN is such that a third-party server breaks your security if it shares certain common elements with yours. In this case, this server uses the same private key as yours. So I'd say that DROWN is not your biggest worry; whoever controls that server (212.82.222.109) can execute silent active network attackers against your users because they have your private key. I would advise you to immediately change your private key. At the same time, request that the certificate with your hostnames is removed from 212.82.222.109.
