### ISSUE TITLE
Wrong DROWN check

### ISSUE THREAD

**Issue by jtkoerting** [ssllabs/ssllabs-scan#495]
Hello,
we are an ISP in germany and - as your ssllabs servercheck is great in general - many customers check their servers with us with your online tool.

The problem is, that the DROWN check is wrong but grading all tests down to F.

The Problem in your DROWN Test is, that it is taking all servers with the same hostname into account. We have thousands of servers - all using a CNAME under one hostname. But only a handful of very, very old system are sharing the same key with SSLv2. More than 99,9% don't do that (not sharing the key nor offering SSLv2 at all), but rated the same, wrong way.

As this is bringing nearly all of our servers in a wrong discredit we ask you to change the way the check is done, as an complete downgrade to F is a really hard way to judge a wrong test.

In the end, you provide a great service that is well known to it's accuracy. So that way of testing and judging is absolutely fitting into this scheme.

Many thanks in advance
Jimmy

**Comment by bhushan5640** [comment]
Hello Jimmy,
 
Scenarios when DROWN affects servers that don’t (or never had) SSL v2 enabled:
1) An RSA key from test server is reused on another server that has SSL v2 enabled or
2) A certificate of another server with SSL v2 enabled is valid for the test server.
 
For DROWN, we have to look for the reuse of the server’s RSA keys and/or certificate hostnames on other servers. For this, SSL Labs uses Censys API to find such servers. Then, we perform real-time checks on those other servers if they reuse key/hostname and support SSL v2.

For the second scenario (certificate hostname reuse), CVE-2016-0703 makes this attack possible in real-time, the attacker can take the certificate from the vulnerable server (SSL v2 enabled) and attack any other server where the certificate matches. The attacker doesn’t need the corresponding private key, and the key doesn’t even need to be the same as on the target server. A complete explanation is available in the DROWN paper [here](https://drownattack.com/drown-attack-paper.pdf). 
 
For both scenarios, users can avoid this issue by disabling the SSLv2 protocol in all their SSL/TLS servers. Under “Protocol Details” section of SSL Labs results where we report the DROWN findings, the IP address of the vulnerable server will be listed. If you disable SSLv2 on those servers, test server will not be downgraded to F grade because of DROWN.

Please PM the impacted domain name to verify if there is any issue @ [blokhande](https://community.qualys.com/people/blokhande). You may also check complete details about SSL Labs drown test implementation [here](https://blog.qualys.com/securitylabs/2016/03/04/ssl-labs-drown-test-implementation-details).
