### ISSUE TITLE
ticketbleed

### ISSUE THREAD

**Issue by hansgoes** [ssllabs/ssllabs-scan#538]
Dear SSLlabs,

We don't see ticketbleed in the API documentation.
However we receive this in the JSON output : 
     "ticketbleed" : 1,

Interesting because the ssl labs analyser shows "not vurnerable" but we interpret the "1" as vurnerable.

Can you clarify and update documentation ?

thanks,
Hans Goes

**Comment by bhushan5640** [comment]
You must be using API v3.
API V3 document does have it:
https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs-v3.md

ticketbleed - results of the ticketbleed CVE-2016-9244 test:
-1 - test failed
0 - unknown
1 - not vulnerable
2 - vulnerable and insecure

**Comment by hansgoes** [comment]
thank you

**Comment by seccubus** [comment]
Seccubus master branch is now up to date. Any concrete plans to provide an API or structured JSON for api consumers so that we don’t have to keep our programs upnto date after every api change/addition?

Sent with big fingers from a small keyboard, don't blame me for typios please...
________________________________
