### ISSUE TITLE
ROBOT Attack

### ISSUE THREAD

**Issue by RobTho** [ssllabs/ssllabs-scan#549]
Please consider to check servers if affected by https://robotattack.org/

**Comment by bhushan5640** [comment]
we have added test to detect ROBOT attack on our dev server : https://dev.ssllabs.com
![img_20171213_072227](https://user-images.githubusercontent.com/6083185/33917865-95c06964-dfd6-11e7-9726-02c8735c4f0d.jpg)

https://twitter.com/BhushanLokhande/status/940622951396753409

**Comment by adamcaudill** [comment]
Is this check exposed in the API? The v3 API documentation hasn't been updated in a while.

**Comment by bhushan5640** [comment]
API v3 Doc is updated:
https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs-v3.md

**bleichenbacher** - results of the Return Of Bleichenbacher's Oracle Threat (ROBOT) test:
-1 - test failed
0 - unknown
1 - not vulnerable
2 - vulnerable (weak oracle)
3 - vulnerable (strong oracle)
4 - inconsistent results

**Comment by adamcaudill** [comment]
Thanks @bhushan5640, much appreciated!

**Comment by agl** [comment]
AppEngine custom domains (for example, guide.duo.com on 216.58.192.19) report as vulnerable to ROBOT. However, they are terminated with BoringSSL, same as the rest of Google, and so we believe that's a false positive.

Is it possible to better understand the tests that are being run here so that we can figure out why this being flagged?

(The custom-domain endpoint is special in that it requires SNI. Perhaps some ROBOT tests are sending SNI and others not and the resulting difference in behaviour is being interpreted as a Bleichenbacher oracle?)

**Comment by streckus** [comment]
I have a similar situation as @agl, a server flagged as vulnerable to ROBOT on ssllabs.com, but on robotattack.org I get the response "This is ideal!". The results look very similar to those for guide.duo.com (also requires SNI, etc.), so I think this is a false positive, too. This should be resolved before Febuary when this vulnerability will set the overall grade to F.

**Comment by bhushan5640** [comment]
@agl__ SSL Labs test is similar to the ROBOT authors original script, except SSL Labs test supports SNI.

For guide.duo.com robotattack.org incorrectly reports that "This host does not support RSA encryption ciphers." But RSA encryption ciphers are supported. SSL Labs is able to detect ROBOT vuln in such cases whereas robotattack.org don't.

I am investigating if guide.duo.com is a false positive. But it does support problematic RSA key exchange ciphers.

**Comment by bhushan5640** [comment]
@streckus please share the domain you think is a false positive. you can inbox me on https://twitter.com/BhushanLokhande

**Comment by streckus** [comment]
@bhushan5640 the domain I got a ROBOT vulnerability displayed for is www.musikverein-randegg.de. The certificate was provided by a shared hosting provider (Strato AG) and should according to their advertising be issued by Symantec.

**Comment by molnarg** [comment]
Note that www.google.com supports more TLS_RSA ciphers than guide.duo.com and still it's not marked as vulnerable.

**Comment by bhushan5640** [comment]
@agl @molnarg Fix is deployed which incorrectly marked some BoringSSL hosts vulnerable. The bug was not specific to the SNI. Fix deployed on https://dev.ssllabs.com

@streckus www.musikverein-randegg.de found vulnerable in our tests. you can refer this for mitigation
https://community.qualys.com/thread/17842-requirements-for-being-labeled-as-vulnerable-to-robot

**Comment by kelbyludwig** [comment]
@bhushan5640 What did you do to address the `guide.duo.com` false positive? There are other tools which seem to have similar issues (https://github.com/nabla-c0d3/sslyze/issues/282).

**Comment by bhushan5640** [comment]
It was implementation issue: Encrypted PMS size should be the exact size of modulus_bytes (server public key). For one bad PMS leading zero got truncated in encrypted PMS. The host terminated connection instead of "Bad record mac 20" for SSL Labs test.

In case of sslyze, Client key exchange looks malformed when it receives TLS Alert 50 (Decode error) for guide.duo.com.

**Comment by chungangus** [comment]
I have Citrix to handle the SSL session (which has been patched) for the web server behind but the results still show vulnerable (oracle is weak).
Is there any false positive on Citrix testing?

**Comment by bhushan5640** [comment]
For any issues separate ticket can be created
