### ISSUE TITLE
DNS CAA not recognized

### ISSUE THREAD

**Issue by McKinleyGroup** [ssllabs/ssllabs-scan#597]
See:
https://www.ssllabs.com/ssltest/analyze.html?d=cloudinsidr.com
versus:
https://caatest.co.uk/cloudinsidr.com

![image](https://user-images.githubusercontent.com/888075/38335380-f7003eae-3812-11e8-9777-0f9d6ef57b59.png)

![image](https://user-images.githubusercontent.com/888075/38335446-2c79f930-3813-11e8-90e7-ce1a28be60f8.png)

**Comment by bhushan5640** [comment]
Its the issue because of https://github.com/ssllabs/ssllabs-scan/issues/554

SSL Labs uses google public DNS
https://dns.google.com/resolve?name=cloudinsidr.com&type=CAA

As it is now reflected on the Google dns, SSL Labs will see the CAA records
![image](https://user-images.githubusercontent.com/6083185/38463878-36f3657a-3b21-11e8-8fdc-adfbd7a92164.png)
