### ISSUE TITLE
SSL Labs showing incorrect TLS status

### ISSUE THREAD

**Issue by ndesimone** [ssllabs/ssllabs-scan#686]
This is a continuation of #685 (sorry, I can't figure out how to reopen an issue).

I am using Cloudflare WAF and I have TLS 1.0 and 1.1 disabled for my site https://www.milkstork.com:

![2019-02-06 04-43-24](https://user-images.githubusercontent.com/1914205/52342374-15f4ad00-29ca-11e9-8181-ca7098dae564.png)

SSL Labs is showing TLS 1.1 is disabled, but TLS 1.0 is still enabled. 

![2019-02-06 04-49-37](https://user-images.githubusercontent.com/1914205/52342571-a6cb8880-29ca-11e9-90ed-302e927ac4c9.png)

I've used an another scanner that is showing that https://www.milkstork.com is not offering 1.0 or 1.1 (as expected).  I can attach those result a little later when I'm in the office.

@tamthing validated SSL Labs results using OpenSSL, but I can't reproduce those results.  Here's what I'm getting from OpenSSL:

`openssl s_client -connect www.milkstork.com:443 -tls1_2
... stuff deleted ...
Verify return code: 20 (unable to get local issuer certificate)`

`openssl s_client -connect www.milkstork.com:443 -tls1_1
... stuff deleted ...
 Verify return code: 20 (unable to get local issuer certificate)`

`openssl s_client -connect www.milkstork.com:443 -tls1_2
... stuff deleted ...
Verify return code: 0 (ok)` 

This implies that 1.0 and 1.1 are disabled (i.e. Cloudflare is working correctly) and the TLS 1.0 report in SSL Labs is incorrect.

**Comment by drwetter** [comment]
The verify return code is just stating that the certificate chain can't be verified. 

Probably you end up on different or a default host at cloudflare.

Speaking of it. Your command line is wrong in the first place as the -servername argument is missing.
-- 
Sent from my mobile. Excuse my brevity&typos+the phone's autocorrection

**Comment by tamthing** [comment]
@ndesimone  Below are the screenshots when I tried to connect to www.milkstork.com, one with servername parameter, other without.

with servername:
<img width="504" alt="milk_stork_sni" src="https://user-images.githubusercontent.com/1249663/52413432-9bca4280-2b07-11e9-9298-969ee7ebcf95.png">

without servername:
<img width="506" alt="milkstork_no_sni" src="https://user-images.githubusercontent.com/1249663/52413441-a8e73180-2b07-11e9-96ed-08dae682a1af.png">

**Comment by tamthing** [comment]
@ndesimone Your server has a configuration that would negotiate with older clients that do not support SNI. I am not sure if this would help in your case but you can refer this past ticket https://community.qualys.com/thread/14140

**Comment by iterop** [comment]
There does appear to be an ssllabs reporting bug here, TLS 1.0 should be No in this case.

Based on the hypothesis noted by @tamthing, that TLS 1.0 = Yes due to the TLS negotiation with the no-SNI certificate, then TLS 1.1 would be Yes as well, yet the report denotes TLS 1.1 = No.  

I believe ssllabs intention is to not report on TLS negotiated measurements with a certificate that does not support the specified site hostname.  In this case the no-SNI certificate does not support www.milkstork.com, which is accurately noted at the top of the report: "This site works only in browsers with SNI support", due to hostname mismatch in the no-SNI certificate.  Thus the results under Configuration should only reflect the TLS negotiated measurements with certificates that support www.milkstork.com.

To reduce clutter I'll paste only the openssl command and interpreted results below.

IP address used by the ssllabs report 104.25.144.104.

Using openssl to connect to the site www.milkstork.com at 104.25.144.104:

openssl s_client -connect 104.25.144.104:443 -servername www.milkstork.com -tls1_2
 > YES
openssl s_client -connect 104.25.144.104:443 -servername www.milkstork.com -tls1_1
 > NO
openssl s_client -connect 104.25.144.104:443 -servername www.milkstork.com -tls1
 > NO

Using openssl to connect to an IP where www.milkstork.com and thousands of other hostnames are serviced in multi-tenant fashion (thus is not relevant to the report for www.milkstork.com):

openssl s_client -connect 104.25.144.104:443 -tls1_2
 > YES
openssl s_client -connect 104.25.144.104:443 -tls1_1
 > YES
openssl s_client -connect 104.25.144.104:443 -tls1
 > YES
 
SSLlabs results under Configuration/Protocols for site www.milkstork.com at 104.25.144.104:
TLS 1.2 = Yes
TLS 1.1 = No
TLS 1.0 = Yes

Thus there's appears to be a bug somewhere in the reporting that is marking TLS 1.0 = Yes, it should be TLS 1.0 = No.

**Comment by iterop** [comment]
There does appear to be an issue here and it appears to be fairly nuanced.  Notice that TLS 1.1 is denoted "No", which the no-SNI cert configuration does support.

The multi-tenant provider for www.milkstork.com is providing a multi-tenant certificate (via a long list of SANs) on both SNI and no-SNI based connection. (They are also providing both RSA and ECDSA certs, depending on client support).  More importantly to this case however, the provider supports different TLS negotiation settings per hostname for the SNI based cert, but are not able to do this for the no-SNI based cert which also contains a match for www.milkstork.com.

For this case www.milkstork.com does support different TLS negotiation settings depending upon whether the client supports SNI or not.

It would be less ambiguous if the report denoted the TLS negotiation measurements based on no-SNI and SNI.  Still though, it seems to be an issue (ambiguity) here that: TLS 1.1 = No while TLS 1.0 = Yes.

**Comment by ndesimone** [comment]
Thanks @iterop.  I appreciate the detail.

**Comment by nayankakati** [comment]
Closing this - please reopen if required.
Thanks
