### ISSUE TITLE
ISRG Root on Firefox

### ISSUE THREAD

**Issue by theandrewbailey** [ssllabs/ssllabs-scan#716]
New Let's Encrypt certificates on the latest Firefox release use the ISRG Root X1 certificate, not DST Root CA X3. On the SSL Report, isn't the Mozilla tab under Certification Paths supposed to be equivalent to Firefox's trust path, since it uses the Mozilla CA trust store?

![image](https://user-images.githubusercontent.com/4029815/58642538-9453c280-82cb-11e9-8924-0cd7230d8e8e.png)

**Comment by naumanshah03** [comment]
Hi @theandrewbailey 

Unable to reproduce the issue on Mozilla Firefox 67.0, the certificate roots to DST Root CA X3 in the browser instead of ISRG Root X1 as mentioned by you. Do let us know with your browser used to reproduce the issue.

For your reference:
![image](https://user-images.githubusercontent.com/22236992/58702310-14108880-83c3-11e9-83e2-9c6f10d37303.png)

FYI, [Mozilla ROOT CA's used in SSL Labs](https://api.ssllabs.com/api/v3/getRootCertsRaw?trustStore=1) has both DST Root CA X3 and ISRG Root X1

Similarly, check the list of the CA certificate in [Mozilla trust store](https://hg.mozilla.org/mozilla-central/raw-file/tip/security/nss/lib/ckfw/builtins/certdata.txt) which has both DST Root CA X3 and ISRG Root X1

**Comment by theandrewbailey** [comment]
It was also on Firefox 67. I've verified that it has both the DST and ISRG roots, but this particular installation/profile chooses the ISRG root. A Firefox Developer Edition install on the same machine also chooses the ISRG root.

On another machine I have, it uses the DST root, as you demonstrated.

**Comment by theandrewbailey** [comment]
I think I've figured out what's going on:

I've visited the Let's Encrypt test site that uses the intermediate certificate signed by the ISRG root ( https://valid-isrgrootx1.letsencrypt.org/ ) on those Firefox installs. The server test confirms this: https://www.ssllabs.com/ssltest/analyze.html?d=valid-isrgrootx1.letsencrypt.org . Once Firefox visits that site, it uses that ISRG intermediate for other Let's Encrypt signed certificates from then on.

**Comment by naumanshah03** [comment]
Hi Andrew,

This doesn't seem to be normal behavior. We cannot achieve this behavior in SSL Labs.
You can check with the Firefox team for this behavior of their application.

Regards,
Nauman Shah
