### ISSUE TITLE
Assessment failed: Unexpected failure

### ISSUE THREAD

**Issue by ghost** [ssllabs/ssllabs-scan#760]
Hello,

I try the url : https://www.ssllabs.com/ssltest/analyze.html?d=h9236.aareonit.fr
Or https://dev.ssllabs.com/ssltest/analyze.html?d=h9236.aareonit.fr
On dev and production system, I get the same error.

I get these errors after the message :
```
Please wait... 84% complete
Determining available cipher suites
```

Thank a lot.

**Comment by naumanshah03** [comment]
After testing and verifying the issue following things were observed:

SSL Labs is failing at different locations and not at exactly one location. While testing for once the test passed completely.

Then to confirm the issue I used OpenSSL with below command multiple times and it was found that the server sometimes fails the handshake with a handshake failure error. This happens because the server did not respond to the request.
`openssl s_client -connect 80.250.140.142:443 -tls1_2 -servername h9236.aareonit.fr`

**Conclusion:** Server is responding inconsistently hence there is no issue with ssllabs
