### ISSUE TITLE
More secure server capped at lower grade then a less secure server (B vs A)???

### ISSUE THREAD

**Issue by ZackInMA** [ssllabs/ssllabs-scan#764]
So I have a server that supports TLS 1.0, 1.1, and 1.2. It also accepts ciphers that do not use forward secrecy. It currently receives an A in your scans. I have another server that only accepts TLS 1.2 and only ciphers with forward secrecy. It's capped at a B.

How is it the less secure server receives a higher grade? See for your yourself.

STG.Xpressreg.Net (more secure server capped at B)
Xpressreg.Net (less secure server receives and A)

**Comment by RobTho** [comment]
TLS 1.0/1.1 not cause degrade yet, this will happen next year
The root cause why STG is degraded, is that it does not support AEAD ciphers (GCM)
If supports FS but not with GCM ciphers
vice versa the non STG supports GCM but not with FS on same cipher (so GCM or FS)

I saw Xpressreg.Net is IIS 8.5 but unfortunally Server 2012R2 does not support  the most common 

TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

But If your 2012R2 is fully patched you will be able to use

TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
which are AEAD and FS (DHE just a bit slower than ECDHE)

or if you switch over to a ECDSA Certificate
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384_P384
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256_P256
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256_P384

To get the most common
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
with IIS you would need to use Server 2016 or later
