### ISSUE TITLE
Err: Unexpected failure for hostname tenant-dot-pitc-shared-dev.appspot.com

### ISSUE THREAD

**Issue by rahuldev247** [ssllabs/ssllabs-scan#789]
2020/04/08 12:43:58 [INFO] Assessment starting: https://tenant-dot-pitc-shared-dev.appspot.com/
2020/04/08 12:44:26 [INFO] Assessment complete: https://tenant-dot-pitc-shared-dev.appspot.com/ (2 hosts in 22 seconds)
    2607:f8b0:4005:80a:0:0:0:2014: Err: Unexpected failure
    172.217.6.84: Err: Unexpected failure
I have read that this might be due to newly enabled / disabled ciphers or multiple ciphers behind ELB.
Could you verify the hostname and let me know what needs to be enabled or disabled ?

**Comment by rahuldev247** [comment]
hi any findings on this ?

**Comment by tamthing** [comment]
Hi @rahuldev247 ,

This issue occurs during a handshake where we modify the compression method in the handshake bytes. From what I see it looks like a case of intolerance by your server. To give you a clearer picture, please check the Wireshark screenshots below. The first one is where the compression method sent is NULL and the handshake is successful.

<img width="708" alt="null_compressionmethod" src="https://user-images.githubusercontent.com/1249663/81145491-00d34900-8f94-11ea-830b-e4c496ac677a.png">


In the second one, we modify the compression method and this results in handshake failure, which otherwise, in a normal server would have resulted in successful handshake(I tried with another server for the same ciphersuite).

<img width="705" alt="deflate_compressionmethod" src="https://user-images.githubusercontent.com/1249663/81145525-0b8dde00-8f94-11ea-9cae-74e60f6dca17.png">

You also mentioned that you recently disabled some ciphersuites. You can try again by enabling few  ciphersuites and see if the test passes. Or maybe you can get in touch with your service provider for the intolerance.

**Comment by rahuldev247** [comment]
Thanks a lot @tamthing , will take this forward to the service provider.
