### ISSUE TITLE
Result strange when server uses dual EC plus RSA cert

### ISSUE THREAD

**Issue by MaxMueller-crypto** [ssllabs/ssllabs-scan#797]
when using the RSA cert only, the DH has the same with as the RSA key (4096 bits),
but when using it together with the EC cert, the DH shows only 1024 bit(!) and the strange thing this:
![screenSSLlabs](https://user-images.githubusercontent.com/64576387/80679106-89e21000-8abc-11ea-84bd-40a26c4ffc5c.png)
here the ciphersuite list with RSA cert only
![screenSSLlabsRSAonly](https://user-images.githubusercontent.com/64576387/80679343-fc52f000-8abc-11ea-9f3d-7dc2b16bf223.png)
and here with both certs EC and RSA
![screenSSLlabsbothECandRSA](https://user-images.githubusercontent.com/64576387/80679368-08d74880-8abd-11ea-9e47-61eca49c3ceb.png)

**Comment by naumanshah03** [comment]
We have multiple clients for handshake simulation. Amongst these clients I saw different DHParam results for the following clients (Client name, version, and SNI/No-SNI):

- Android 2.3.7 (NoSNI): DH Key strength=4096, dhP=512, dhG=1, dhYs=512
- Java 6u45 (NoSNI): DH Key strength=4096, dhP=-1, dhG=-1, dhYs=-1
- OpenSSL 0.9.8y (SNI): DH Key strength=1024, dhP=128, dhG=1, dhYs=128

Note: All the values for DH key Strength, dhP, dhG, and dhYs are taken from the API v3. Since Java 6u45 does not support dh strength above 1024 hence all the other values dh values are set to -1.

With further analysis by using OpenSSL tool:
1. First request with NoSNI and DHE-RSA-AES128-SHA cipher
`/opt/ssllabs/bin/openssl s_client -connect www.ipv6help.de:443 -cipher DHE-RSA-AES128-SHA`
2. Second request with SNI and DHE-RSA-AES128-SHA cipher
`/opt/ssllabs/bin/openssl s_client -connect www.ipv6help.de:443 -servername www.ipv6help.de -cipher DHE-RSA-AES128-SHA`

**Note:** to check for DH param we should check the dhP parameter which is actually in bytes and we multiple it by 8 and convert it to bits (128 bytes = 1024 bits OR 512 bytes = 4096 bits)
In Wireshark check for server key exchange packet to get the information for DH param.

Conclusion: Your server is configured for different DHParam i.e 4096 and 1024, NoSNI, and SNI respectively. It is not a bug in SSLLabs
