### ISSUE TITLE
SSL test certificate errors

### ISSUE THREAD

**Issue by CaptainFrosty** [ssllabs/ssllabs-scan#875]
I would be grateful if someone took the time to inform this non-expert of why I might receive the following SSL errors on the test site:
___
![SmartSelect_20220128-143428_Privacy Browser](https://user-images.githubusercontent.com/8523498/151613273-1684a8d5-995e-4286-b741-06cc0058fe2f.jpg)
![SmartSelect_20220128-143414_Privacy Browser](https://user-images.githubusercontent.com/8523498/151613277-36ef21f9-651f-478c-8d99-7b3e57820d03.jpg)
![SmartSelect_20220128-143402_Privacy Browser](https://user-images.githubusercontent.com/8523498/151613281-0372b89d-86a8-4f97-9b37-9f9eb99ee15f.jpg)
![SmartSelect_20220128-143348_Privacy Browser](https://user-images.githubusercontent.com/8523498/151613284-ba94250a-a5ab-40a1-bfe8-f1dc2833b625.jpg)

___
Thanks.

**Comment by naumanshah03** [comment]
Hi @CaptainFrosty 

This is our client test and we have different configuration on SSLLabs in order to test vulnerabilities and protocols. Based on the failure of connection with the above-mentioned SSL Connection we generate our report for the client that is being tested.

You can check the network tab in your browser. This is the expected behavior for the client test

Regards,
Nauman Shah

**Comment by CaptainFrosty** [comment]
Oh, I see. So part of the tests rather than an indication of a problem with them. Sorry for the misunderstanding. I'll be sure to check the console next time. I was on a WebView-based mobile browser at the time so I didn't have much for quick debugging at hand.
