### ISSUE TITLE
Handshake simulation does not acknowledge, that old Android devices do not have ISRG X1 in the trust store

### ISSUE THREAD

**Issue by dilyanpalauzov** [ssllabs/ssllabs-scan#877]
The websites mail.aegee.org and ldap.aegee.org both use Lets Encrypt Certificates.  The former uses the chain: private-certificate → R3 → ISRG X1 → DST ROOT CA X3 where X3 is self-signed.  The latter uses the chain private-certificate → R3 → ISRG X1, where X1 is self-signed

According to https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/ the longer chain, including the expired DST X3 will work on old Android devices, where the shorter chain will fail.

The handshake simulations at https://www.ssllabs.com/ssltest/analyze.html?d=mail.aegee.org and https://www.ssllabs.com/ssltest/analyze.html?d=ldap.aegee.org both show, that both websites will load on old Android.

This conclusion is not correct.  On some very old Android (I guess 7 is such old), the X1-only chain will not load, because X1 is not in the trust store.

**Comment by kimboslice99** [comment]
Just noticed this myself, would be nice if the site correctly reflected what client devices see

**Comment by naumanshah03** [comment]
Hi @dilyanpalauzov / @kimboslice99 

This is expected behavior because in SSLLabs we do not perform Trust store scanning for the handshake simulation and the same has been mentioned in the reports.
Please refer to the screenshot below
![image](https://user-images.githubusercontent.com/22236992/155377951-188e9a64-c4c7-46e2-8181-2e86a56011f9.png)

**Note:** We have no plans on adding trust store check for handshake simulation

Regards,
Nauman Shah
