### ISSUE TITLE
Assessment failed: Unable to connect to the server

### ISSUE THREAD

**Issue by lethienhongson96** [ssllabs/ssllabs-scan#894]
Hi guys.
when i scan on ssllabs then i face this. ssl is valid
please help, thank you.
![image](https://user-images.githubusercontent.com/66103162/176723814-cef32279-a25b-4d01-a642-b72a1cb9bed5.png)

**Comment by codergaz** [comment]
Most likely there is a firewall preventing connections.

From several networks I have not been able to connect to port 443 of the specified server.

**Comment by naumanshah03** [comment]
Please check if the domain is whitelisted for ssllabs. Also check if the domain is accessible publicly.

There is no issue from SSLLabs side.

Regards,
Nauman Shah

**Comment by naumanshah03** [comment]
Hi @lethienhongson96 

Your domain is not accessible from my machine. Also checked other tools and they're showing as the domain is not reachable from particular regions.

- https://www.websiteplanet.com/webtools/down-or-not/?dorn=https%3A%2F%2Ffbs.mapletree.com.sg%2F
- https://www.site24x7.com/check-website-availability.html
![image](https://user-images.githubusercontent.com/22236992/178431858-8b902002-fd1f-40e2-b529-4795c8d45844.png)

As verified your domain is not reachable from my machine so when checked with other tools it is was found that your sub-domain is only reachable from particular region as seen from the screenshot.

About whitelisting, if you have any firewall then you will have to whitelist ssllabs ip range in order allow complete scanning of your domain. Now since this is an issue with reachability of the domain you can check with your network team about it.

Regards,
Nauman Shah

**Comment by naumanshah03** [comment]
Closing the issue as no response received
