### ISSUE TITLE
HSTS Preloaded in all browsers but Chrome

### ISSUE THREAD

**Issue by paveljanik** [ssllabs/ssllabs-scan#897]
SSLLabs test of www.czebox.cz shows the domain czebox.cz to be HSTS preloaded in all browsers but Chrome.
But in the current Chrome, the page chrome://net-internals/#hsts and HSTS query shows that
```
Found:
static_sts_domain: czebox.cz
static_upgrade_mode: FORCE_HTTPS
static_sts_include_subdomains: true
static_sts_observed: 1656720026
```
ie. the domain is preloaded in Chrome. So SSLLabs test should show it is preloaded in Chrome.

**Comment by naumanshah03** [comment]
Hi @paveljanik 

Thanks a lot for brining up this issue and reporting it.
Found the root cause of the issue that Chromium is not updating the `master` branch and they've moved to the `main` branch for the HSTS preload file.
We have fixed it in SSLLabs a release will follow soon.
![image](https://user-images.githubusercontent.com/22236992/181505586-049daf1d-e16a-49fe-a1fc-452838ea1612.png)

Regards,
Nauman Shah

**Comment by paveljanik** [comment]
@naumanshah03: brilliant!

**Comment by Justasvilg** [comment]
HSTS preloading function appears to be broken for Chrome.  Repro: https://www.ssllabs.com/ssltest/analyze.html?d=account.proton.me

**Comment by sergiozygmunt** [comment]
Is this behavior still expected? In May 2023 I am seeing the same behavior (where the site is listed as HSTS preloaded for all browsers except Chrome)

**Comment by cmason3** [comment]
Seems to be broken still. I can only assume they have an old cached copy of the HSTS list in their Chrome test.

It also looks like no one is really cared as there are no replies from anyone responsible for this.

**Comment by adrelanos** [comment]
Bug confirmed. Still happening.

https://hstspreload.org/?domain=whonix.org says it's preloaded.

https://www.ssllabs.com/ssltest/analyze.html?d=whonix.org says it's not preloaded.

**Comment by paveljanik** [comment]
This is now fixed in the live site.
